In [6]:
# numpy는 벡터 행렬 사용하는 선형대수 계산에서 사용함
!pip install numpy

In [4]:
import numpy as np # 국룰
np.__version__

'2.3.3'

In [6]:
# 1-dimension array
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [8]:
# 2-dimension array
mat = np.array([[10,20,30], [40,50,60]])
print(mat)

[[10 20 30]
 [40 50 60]]


In [11]:
print("vector 타입 :", type(vector))
print("mat 타입 : ", type(mat))

vector 타입 : <class 'numpy.ndarray'>
mat 타입 :  <class 'numpy.ndarray'>


In [ ]:
print(vector)
print("vector 의 축 개수 : ", vector.ndim)
print("vector 의 크기(shape)", vector.shape)

[1 2 3 4 5]
vector 의 축 개수 :  1
vector 의 크기(shape) (5,)


In [15]:
print(mat)
print("mat 의 축 개수 :", mat.ndim)
print("mat 의 크기(shape) :", mat.shape) #2행3열

[[10 20 30]
 [40 50 60]]
mat 의 축 개수 : 2
mat 의 크기(shape) : (2, 3)


In [ ]:
# 2행3열 영행렬 np.zeros(())
zeromat = np.zeros((2,3))
print(zeromat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 2행3열 1행렬 np.ones(())
onemat = np.ones((2,3))
print(onemat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# 모두 원하는 값 넣고싶어 np.full((), n)
imat = np.full((2,3), 10)
print(imat)

[[10 10 10]
 [10 10 10]]


In [25]:
# 대각선이 1이고, 나머지 0인 단위행렬 np.eye(n) => nxn matrix
eyemat = np.eye(3)
print(eyemat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# 정말랜덤값 np.random.random(())
randommat = np.random.random((3,2))
print(randommat)

[[0.37229843 0.04714571]
 [0.67530605 0.35521766]
 [0.70544593 0.0841998 ]]


In [30]:
# Range를 가지고 만드는 배열! np.arange()
rangevec = np.arange(10)
print(rangevec)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
# np.arange(i,j,k) 를 하면 i부터 j-1 까지 k 씩 증가
range_stepvec = np.arange(2,20,4)
print(range_stepvec)

[ 2  6 10 14 18]


In [35]:
# 배열 변경 함수
# .reshape(n,m) 을 하면 n행 m열 matrix로 바꿔준다!!
vec = np.array(np.arange(20))
print(vec)
vec_reshape = vec.reshape(4,5)
print(vec_reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
mat = np.array(([1,2,3], [4,5,6]))
print(mat)

[[1 2 3]
 [4 5 6]]


In [40]:
# Slicing 원하는거만 짤라서 볼 수 있다!! mat[0,0]
# e.g. 원하는 행을 보고싶다 mat[n,:] => n+1 행을 출력함
# e.g. 원하는 열을 보고싶다 mat[:,n] => n+1 열을 출력함
smat = mat[0,:] # 1행 출력
print(smat)
scmat = mat[:,0] # 1열 출력
print(scmat)

[1 2 3]
[1 4]


In [42]:
# indexing 원하는 원소만 뽑아와서 배열로 재구성 할 수 있다!!
mat = np.array([[1,2], [4,5], [6,7]])
print(mat)

[[1 2]
 [4 5]
 [6 7]]


In [44]:
# 2행1열 원소
print(mat[1,0])

4


In [46]:
# 2행1열이랑 3행1열 가지고 만들고싶어
indexing_mat = mat[[1,2], [0,0]]
print(indexing_mat)

[4 6]


In [ ]:
# 연산 또한 자유롭게 가능 
x = np.array([[1,2], [3,4]])
y = np.array([[2,3], [4,5]])

print(x)
print(y)
print(x*y)
z = np.dot(x,y)
print(z)
# x*y와 np.dot(x,y)가 다른 이유
# 행렬곱임!!

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]
[[ 2  6]
 [12 20]]
[[10 13]
 [22 29]]
