In [1]:
# numpy는 벡터 행렬 사용하는 선형대수 계산에서 사용함
pip install numpy

SyntaxError: invalid syntax (3167488478.py, line 2)

In [4]:
import numpy as np # 국룰
np.__version__

'2.3.3'

In [6]:
# 1-dimension array
vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


In [8]:
# 2-dimension array
mat = np.array([[10,20,30], [40,50,60]])
print(mat)

[[10 20 30]
 [40 50 60]]


In [11]:
print("vector 타입 :", type(vector))
print("mat 타입 : ", type(mat))

vector 타입 : <class 'numpy.ndarray'>
mat 타입 :  <class 'numpy.ndarray'>


In [ ]:
print(vector)
print("vector 의 축 개수 : ", vector.ndim)
print("vector 의 크기(shape)", vector.shape)

[1 2 3 4 5]
vector 의 축 개수 :  1
vector 의 크기(shape) (5,)


In [15]:
print(mat)
print("mat 의 축 개수 :", mat.ndim)
print("mat 의 크기(shape) :", mat.shape) #2행3열

[[10 20 30]
 [40 50 60]]
mat 의 축 개수 : 2
mat 의 크기(shape) : (2, 3)


In [ ]:
# 2행3열 영행렬 np.zeros(())
zeromat = np.zeros((2,3))
print(zeromat)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 2행3열 1행렬 np.ones(())
onemat = np.ones((2,3))
print(onemat)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# 모두 원하는 값 넣고싶어 np.full((), n)
imat = np.full((2,3), 10)
print(imat)

[[10 10 10]
 [10 10 10]]


In [25]:
# 대각선이 1이고, 나머지 0인 단위행렬 np.eye(n) => nxn matrix
eyemat = np.eye(3)
print(eyemat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
# 정말랜덤값 np.random.random(())
randommat = np.random.random((3,2))
print(randommat)

[[0.37229843 0.04714571]
 [0.67530605 0.35521766]
 [0.70544593 0.0841998 ]]
