이 파일은 원하는 외부데이터를 읽고 정제하는 과정에서 학습한 기록임!
pandas 패키지를 사용해서 데이터 읽기 가능

In [ ]:
pip install pandas

SyntaxError: invalid syntax (908194820.py, line 1)

In [17]:
import pandas as pd # 국룰
import numpy as np
pd.__version__

'2.3.3'

Pandas는 데이터 처리를 하는 라이브러리임

### 1. Series

In [2]:
sr = pd.Series([17000, 18000, 1000, 5000],
            index = ["피자", "치킨", "콜라", "맥주"])
print('시리즈 출력')
print('-'*15)
print(sr)
# Index와 Value 를 출력가능하다!!

시리즈 출력
---------------
피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [3]:
print('시리즈의 값 : {}'. format(sr.values))
print('시리즈의 인덱스 : {}'. format(sr.index))

시리즈의 값 : [17000 18000  1000  5000]
시리즈의 인덱스 : Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


### 2. DataFrame

In [5]:
# 2차원 List를 매개변수로 전달함 행이랑 열 존재!! 
values = [[1,2,3], [4,5,6], [7,8,9]] # 1행 123, 2행 456, 3행 789
index =  ['one', 'two', 'three']
columns = ['A', 'B', 'C'] # 1열 A, 2열 B, 3열 C

df = pd.DataFrame(values, index, columns)

print('데이터프레임 출력 ')
print('-'*15)
print(df)

데이터프레임 출력 
---------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [6]:
# 또한 값 따로 출력가능
print('DataFrame Index: {}'.format(df.index))
print('DataFrame Columns: {}'.format(df.columns))
print('DataFrame Values : ')
print(df.values)

DataFrame Index: Index(['one', 'two', 'three'], dtype='object')
DataFrame Columns: Index(['A', 'B', 'C'], dtype='object')
DataFrame Values : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# DataFrame Generation Using 'LIST'
data = [
    ['1000', 'Mo', 90.72],
    ['1001', 'by', 12.34],
    ['1002', 'ung', 98.43],
    ['1003', 'hyu', 54.41],
    ['1004', 'nn', 64.12],
    ['1005', 'NY', 99.99],
]

df = pd.DataFrame(data)
print(data)
print(df)

[['1000', 'Mo', 90.72], ['1001', 'by', 12.34], ['1002', 'ung', 98.43], ['1003', 'hyu', 54.41], ['1004', 'nn', 64.12], ['1005', 'NY', 99.99]]
      0    1      2
0  1000   Mo  90.72
1  1001   by  12.34
2  1002  ung  98.43
3  1003  hyu  54.41
4  1004   nn  64.12
5  1005   NY  99.99


In [12]:
# Add Column
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번   이름     점수
0  1000   Mo  90.72
1  1001   by  12.34
2  1002  ung  98.43
3  1003  hyu  54.41
4  1004   nn  64.12
5  1005   NY  99.99


In [21]:
# Data Generation Using Dictionary

data = {
    '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
    '이름' : ['MO', 'by', 'ung', 'nn', 'NY', 'AA'],
    '점수' : [90.72, 12.34, 98.43, 54.41, 64.12, 99.99]
    }

df = pd.DataFrame(data)
print(df)

     학번   이름     점수
0  1000   MO  90.72
1  1001   by  12.34
2  1002  ung  98.43
3  1003   nn  54.41
4  1004   NY  64.12
5  1005   AA  99.99


In [28]:
# 앞에 n개만 보고싶음
# print(df.head(n))
print(df.head(3))

# 뒤에 n개만 보고싶음
# print(df.tail(n))
print(df.tail(3))

# 원하는 열을 보고싶음
# print(df['열이름'])
print(df['이름'])

     학번   이름     점수
0  1000   MO  90.72
1  1001   by  12.34
2  1002  ung  98.43
     학번  이름     점수
3  1003  nn  54.41
4  1004  NY  64.12
5  1005  AA  99.99
0     MO
1     by
2    ung
3     nn
4     NY
5     AA
Name: 이름, dtype: object


In [ ]:
# 이 명령어를 가지고 원하는 외부데이터를 읽을 수 있음!!